version: '3'

volumes:
    node-modules:
services:
  app:
    build:
      context: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app/
      - node-modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
networks:
  developer-seed-tutorial-net:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.218.0/20"